import { Geist } from "next/font/google";
import Topbar from "@/components/layout/Topbar";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import "../styles/globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

const geist = Geist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-heading",
});

export const metadata = {
  title: "Disin Hospital App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geist.className}`}>
      <body>
        <Topbar />
        <Navbar />
        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
